### PR TITLE
Add C++ iostream logging to VS Code terminal window

### PR DESCRIPTION
**Pull request by SamuelAsherRivello**
I'm new to C++.

I tested this only on Windows 11* and VS Code*. It works great.

*Latest public versions as of this commit.

Relates to my issue: 

https://github.com/CapsCollective/raylib-cpp-starter/issues/22

### CODE REVIEW

**Review by jonjondev — CHANGES_REQUESTED** [review]
Changes look fine on our end @SamuelAsherRivello, thanks for adding. Just if you could remove your changes to `main.cpp` that would be best. Also feel free to add your name to the readme as a contributor in the `README.md`.

**Comment by SamuelAsherRivello** [comment]
@jonjondev Thanks. Your feedback is complete and committed. Please review and merge.

**Review by jonjondev — APPROVED** [review]

**Comment by jonjondev** [comment]
@SamuelAsherRivello sorry do you mind rebasing on top of latest? Just want to get a passing CI run before merging.

**Comment by SamuelAsherRivello** [comment]
I think that's beyond my git knowledge level. Ideas?

**Comment by jonjondev** [comment]
If I understand how you're probably set up on your end, it would probably be something like:
```console
git switch origin/main
git remote add base git@github.com:CapsCollective/raylib-cpp-starter.git
git fetch base
git rebase base/main
```

**Comment by SamuelAsherRivello** [comment]
I attempted that with the attached failed results. 


Rather than continue to debug it, I created a fresh branch off main and submitted a new PR addressing your complete feedback. Thanks.

https://github.com/CapsCollective/raylib-cpp-starter/pull/26

**Comment by jonjondev** [comment]
Huh, it reads like SSH isn't setup correctly? Either way, that works! Closing this PR in favour of #26.

**Pull request closed without merging**
